name: Quality Check
run-name: Checking commit by ${{ github.actor }}

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun ci

      - name: Lint
        run: bun run lint

  Style:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun ci

      - name: Style
        run: bun run style

  Check-Types:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun ci

      - name: Check types
        run: bun run check-types

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun ci

      - name: Build
        run: bun run build
